- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  dnf:
    name: [ "lua5.1", "unzip", "gettext", "util-linux-user", "cmake"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  dnf:
    name: ["curl", "htop", "golang", "lsof", "i3", "ccache", "ninja-build", "python3-pip", "dconf-editor", "nvidia-settings"]
  tags:
    - install
    - core

