- name: Install fish
  apt: name=fish
  tags: &tags_for_fish_tasks [ 'install', 'productivity', 'dotfiles', 'fish' ]
    
- name: Change shell to fish
  shell: chsh -s $(which fish)
  tags: *tags_for_fish_tasks

