- name: Install packages
  become: true
  dnf:
    name: [ "tmux", "wireshark", "fzf", "kdenlive", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "shutter" ]
  tags:
    - install
    - productivity
